name: stack

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'
  schedule:
    - cron: "00 15 * * *"

jobs:
  build:
    name: ${{ matrix.os }} (${{ matrix.resolver }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-10.15]
        resolver: ["lts-14", "lts-16", "nightly"]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: "8.8.4"
        stack-version: "2.5.1"
        enable-stack: true

    - name: Install libralies (linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y libcwiid-dev libsdl1.2-dev libsdl-image1.2-dev libsdl-ttf2.0-dev libsdl-mixer1.2-dev libfreenect-dev

    - name: Install libralies (mac)
      if: runner.os == 'macOS'
      # workaround: https://github.com/actions/virtual-environments/issues/1811
      run: |
        brew untap local/homebrew-openssl
        brew untap local/homebrew-python2
        brew update
        brew install libfreenect sdl sdl_image sdl_mixer sdl_ttf pkg-config
        sed -i -e "s/#define main	SDL_main//" /usr/local/Cellar/sdl/1.2.15_2/include/SDL/SDL_main.h

    - name: Install dependencies & Build (Linux)
      env:
        STACK_YAML: stack-${{ matrix.resolver }}.yaml
      if: runner.os == 'Linux'
      run: |
        stack test --only-dependencies
        stack test --fast
        stack install --fast

    - name: Install dependencies & Build (Mac)
      env:
        STACK_YAML: stack-${{ matrix.resolver }}.yaml
      if: runner.os == 'macOS'
      run: |
        stack test --only-dependencies --flag haskanoid:-wiimote
        stack test --fast --flag haskanoid:-wiimote
        stack install --fast --flag haskanoid:-wiimote