name: stack

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'
  schedule:
    - cron: "00 15 * * *"

jobs:
  build:
    name: ${{ matrix.os }} (${{ matrix.resolver }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-10.15]
        resolver: ["lts-14", "lts-15", "nightly"]
        cache-version: ["2020-03-15"]

    steps:
    - uses: actions/checkout@v2
    - uses: mstksg/setup-stack@v2

    - name: Display stack version
      run: stack --version

    - name: Cache ~/.stack
      uses: actions/cache@v1
      with:
        path: ~/.stack
        key: ${{ runner.os }}-${{ matrix.resolver }}-${{ matrix.cache-version }}-stack

    - name: Install libralies (linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y libbluetooth-dev libcwiid-dev libsdl1.2-dev libsdl-image1.2-dev libsdl-ttf2.0-dev libsdl-mixer1.2-dev libfreenect-dev

    - name: Install libralies (mac)
      if: runner.os == 'macOS'
      run: |
        brew update
        brew install libfreenect sdl sdl_image sdl_mixer sdl_ttf pkg-config

    - name: Configure
      run: stack config set resolver ${{ matrix.resolver }}

    - name: Install dependencies & Build (Linux)
      if: runner.os == 'Linux'
      env:
        STACK_YAML: stack-${{ matrix.resolver }}.yaml
      run: |
        stack test --only-dependencies
        stack test --fast
        stack install --fast

    - name: Install dependencies & Build (Mac)
      if: runner.os == 'macOS'
      env:
        STACK_YAML: stack-${{ matrix.resolver }}.yaml
      run: |
        stack test --only-dependencies --flag haskanoid:-wiimote
        stack test --fast --flag haskanoid:-wiimote
        stack install --fast --flag haskanoid:-wiimote